python deep_sdf_prior.py --data_dir /home/nicolai/sra/data/ShapeNetCorev2 --output_dir ./shapenet --category shapenet 
python deep_sdf_prior.py --data_dir /home/nicolai/sra/data/ShapeNetCorev2 --output_dir ./shapenet --category shapenet 
python deep_sdf_prior.py --data_dir /home/nicolai/sra/data/ShapeNetCorev2 --output_dir ./shapenet --category shapenet 
python deep_sdf_prior.py --data_dir /home/nicolai/sra/data/ShapeNetCorev2 --output_dir ./shapenet --category shapenet 
python deep_sdf_prior.py --data_dir /home/nicolai/sra/data/ShapeNetCorev2 --output_dir ./shapenet --category shapenet 
python deep_sdf_prior.py --data_dir /home/nicolai/sra/data/ShapeNetCorev2 --output_dir ./shapenet --category shapenet 
python deep_sdf_prior.py --data_dir /home/nicolai/sra/data/ShapeNetCorev2 --output_dir ./shapenet --category shapenet 
python deep_sdf_prior.py --data_dir /home/nicolai/sra/data/ShapeNetCorev2 --output_dir ./shapenet --category shapenet 
python deep_sdf_prior.py --data_dir /home/nicolai/sra/data/ShapeNetCorev2 --output_dir ./shapenet --category shapenet 
python deep_sdf_prior.py --data_dir /home/nicolai/sra/data/ShapeNetCorev2 --output_dir ./shapenet --category shapenet 
python deep_sdf_prior.py --data_dir /home/nicolai/sra/data/ShapeNetCorev2 --output_dir ./shapenet --category shapenet 
python deep_sdf_prior.py --data_dir /home/nicolai/sra/data/ShapeNetCorev2 --output_dir ./shapenet --category shapenet 
python deep_sdf_prior.py --data_dir /home/nicolai/sra/data/ShapeNetCorev2 --output_dir ./shapenet --category shapenet 
python deep_sdf_prior.py --data_dir /home/nicolai/sra/data/ShapeNetCorev2 --output_dir ./shapenet --category shapenet 
python deep_sdf_prior.py --data_dir /home/nicolai/sra/data/ShapeNetCorev2 --output_dir ./shapenet --category shapenet 
python deep_sdf_prior.py --data_dir /home/nicolai/sra/data/ShapeNetCorev2 --output_dir ./shapenet --category shapenet 
python deep_sdf_prior.py --data_dir /home/nicolai/sra/data/ShapeNetCorev2 --output_dir ./shapenet --category shapenet 
python deep_sdf_prior.py --data_dir /home/nicolai/sra/data/ShapeNetCorev2 --output_dir ./shapenet --category shapenet 
python deep_sdf_prior.py --data_dir /home/nicolai/sra/data/ShapeNetCorev2 --output_dir ./shapenet --category shapenet 
python deep_sdf_prior.py --data_dir /home/nicolai/sra/data/ShapeNetCorev2 --output_dir ./shapenet --category shapenet 
